### ISSUE TITLE
Forum Suggestions that I like and need to be approved for addition:

### ISSUE THREAD

**Issue by IvanTheOven** [UnraveledMC/UnraveledMCMod#10]
- Remove automatic 2-5 minute temp bans.

-  Add commands to view how many punishments a player has received, who it was given from, and why.

-  Make the infamous "naughty, naughty, boy" line more gender friendly.

-  Be able to toggle the use of redstone like TFM now; but not use marco's crappy code.

-  Make GTFO stop automatically rolling back a player.

-  A command that unloads chunks (not getting added)

-  Add a punishment GUI (I don't think this will be added, but we'll see)

-  A command to allow staff to vanish completely from regular operators.

**Comment by CreeperSeth** [comment]
Unloading chunks causes more resources to be used when they have to be loaded back in

**Comment by OxLemonxO** [comment]
I don't agree with:
Make the infamous "naughty, naughty, boy" line more gender friendly.
It's there because it's funny.

**Comment by LightWarp** [comment]
To be honest yeah, I'd just leave it at "naughty, naughty, boy"; and i'm also not a fan of /gtfo NOT rolling back a player, cause... its extra work and has to be done quickly. The 2 - 5 min bans need to go tho, it's annoying if a kid appeals on the forums about it.

**Comment by ZeroEpoch1969** [comment]
- Gender neutralized the naughty message
- Removed 5 minute bans
- The ban command never did auto rollback a player
Not doing:
- Punishment logs and a gui are completely gay and a waste of time to add not to mention it's going to be deleted like 50,000 times
- Fuck toggling redstone whats the point if you can't even find what's causing it
- You aren't going to be able to hide an admin completely from ops

**Comment by OxLemonxO** [comment]
why remove the 5 minute bans @ZeroEpoch1969

**Comment by ZeroEpoch1969** [comment]
@OxLemonxO bc no one learns from it and a lot of staff wanted it gone
