### ISSUE TITLE
WorldEdit Forbidden Blocks

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC/UnraveledMCMod#37]
WorldEdit should work like the old good days where it would deop you if you used lava, sand, tnt etc.
The block IDs should be configurable.

**Comment by robingall2910** [comment]
this isn't a bug, it's an enhancement tf

**Comment by aggelosQQ** [comment]
accepted though

**Comment by robingall2910** [comment]
no one said who's gonna do it though

**Comment by aggelosQQ** [comment]
you are 5, whoever wants to do it can assign it to him.

**Comment by ShadowArmadyl** [comment]
Why do we need this, though?
Water and lava work just like any block, CoreProtect can roll it back and flowing is disabled.
TNT serves no purpose since explosions are disabled.

With the plugin de-opping the player or not, either way you'll need an administrator to deal with the situation. Water and lava are also useful building items and I've seen TNT used decoratively.

**Comment by aggelosQQ** [comment]
@ShadowArmadyl I don't really care about TNT but water & lava is used to grief a lot more than to build.
There are random spheres of lava literally all over the place.
There's literally no point on having them enabled.

**Comment by robingall2910** [comment]
Then just simply roll it back like how he said?

**Comment by aggelosQQ** [comment]
guess you're against with anything i'm saying? huh
it's not just one single person or a place, and why would i do that when it can just be prevented?

**Comment by robingall2910** [comment]
everyone is at this matter, there's literally other things that you can possibly do right now instead.

**Comment by aggelosQQ** [comment]
like?

**Comment by ShadowArmadyl** [comment]
@aggelosQQ As a builder I beg to differ. There's no point disabling water and lava considering they behave like any other block.

**Comment by aggelosQQ** [comment]
m

**Comment by aggelosQQ** [comment]
Alright then.
We'll keep lava and water unblocked and see how it goes.
