### ISSUE TITLE
New Shop Item: Disco

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC/UnraveledMCMod#38]
I'd like our current /disco command become a brand new /shop item that costs 100 coins for lifetime use.

This would enable a /disco command which would give you a full leather armor set that changes colors quickly. That command could be togglable.

On: will keep changing colors.
Off: will stop changing colors on the leather armor the user's wearning.

Suggestion thread: http://unraveledmc.com/forum/showthread.php?tid=1213

**Comment by CreeperSeth** [comment]
The plugin that does the color changing would still work even if players didn't buy it as they just need to put leather armor on.

**Comment by OxLemonxO** [comment]
@CreeperSeth edit the plugins source?

**Comment by aggelosQQ** [comment]
Can't you like implement the feature on UMCM and delete that plugin?

**Comment by CreeperSeth** [comment]
It was free from the start and it's such a pointless item no one ever really uses. Just gonna close this now.
