### ISSUE TITLE
Hide IPs from Public View

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC/UnraveledMCMod#39]
IPs from broadcast messages should be hidden or atleast ranged.

The only way AN ADMIN will be able to find an IP (for permban requests) is to /seen the user or maybe having a command /findip <user> where it's admin-only and shows all the IPs the specified user has logged on with.

**Comment by OxLemonxO** [comment]
ips are not personal information -.-

**Comment by aggelosQQ** [comment]
Still, I don't really like seeing IPs in chat.

**Comment by robingall2910** [comment]
I would say leave it as is, what's the true point of hiding IPs?

**Comment by aggelosQQ** [comment]
i will sleep better at night

**Comment by robingall2910** [comment]
I wonder what else keeps you up at night then

**Comment by aggelosQQ** [comment]
Only that

**Comment by aggelosQQ** [comment]
@CreeperSeth do it please.

**Comment by CreeperSeth** [comment]
when I feel like it

**Comment by OxLemonxO** [comment]
there
is no
point -,.-

**Comment by ShadowArmadyl** [comment]
Hiding something as public as an IP would be useless.

**Comment by OutOfYourMind** [comment]
Hiding an IP would be useless, or you could just do for example: 127.0.*.*

**Comment by aggelosQQ** [comment]
It's none of OP's business to have somebody's IP address.

**Comment by AvalancheYT** [comment]
While we are at it, hide IPs from admins.

**Comment by typhlosion147** [comment]
IPs are public information, there is no point in hiding them.

**Comment by OxLemonxO** [comment]
@aggelosQQ Everyone could have an IP address.
"[insert player name here] click this link!". Goes link to an ip logger, boom, IP.
Any website you visit has your IP.
Any server you visit has your IP. Anything you do on your internet, has your IP.
