### ISSUE TITLE
/fuckoff is broken

### ISSUE THREAD

**Issue by typhlosion147** [UnraveledMC/UnraveledMCMod#41]
Mind trying to fix this?

**Comment by robingall2910** [comment]
could you at least provide log errors or something lol

**Comment by typhlosion147** [comment]
robin, there are no logs-- It doesn't expel people automatically like it should, it literally just teleports them around you lmao

**Comment by OxLemonxO** [comment]
that's what it does on tf too

**Comment by CreeperSeth** [comment]
I'm thinking about removing /fuckoff because it's so useless and just annoys everyone

**Comment by OxLemonxO** [comment]
no bad @CreeperSeth it's the best command
