### ISSUE TITLE
Can i 

### ISSUE THREAD

**Issue by Barkpuppy1** [UnraveledMC/UnraveledMCMod#42]
Can i use some of code in DogFreedomCore?

**Comment by robingall2910** [comment]
@UnraveledMC/owners can help you on that

**Comment by aggelosQQ** [comment]
@creeperseth

**Comment by OxLemonxO** [comment]
@CreeperSeth

**Comment by CreeperSeth** [comment]
As long as you don't claim it as your own I'm fine with it.
