### ISSUE TITLE
Adding coins 

### ISSUE THREAD

**Issue by SynfulYT** [UnraveledMC/UnraveledMCMod#43]
Recently after a break from UMC and I have come back and re-instated for STA

I have seen that when I vote or type those letters in the chat, it says I have been given 8 coins but I do /coins and it does not work that has made @samennis1 do /ms coins add

**Comment by CreeperSeth** [comment]
What is the exact message that says you have recieved 8 coins? If it wasn't the message after executing the command then something is misconfigured.

**Comment by SynfulYT** [comment]
I believe it is fixed now
