### ISSUE TITLE
UnraveledMCMod won't Compile.

### ISSUE THREAD

**Issue by LightWarp** [UnraveledMC/UnraveledMCMod#46]
This is at the beginning. it asks for the TFM Lib stuff

The POM for org.spigotmc:spigot:jar:1.11.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for net.pravian:aero:jar:2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for net.totalfreedom:bukkittelnet:jar:4.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for net.totalfreedom:tf-worldedit:jar:6.1.0-TF is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for net.totalfreedom:tf-essentials:jar:2.0-TF is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for me.libaryaddict:LibsDisguises:jar:9.2.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for net.dv8tion:JDA:jar:2.3.0_379 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

then a whole lot of junk...

Then at the end: 
To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

i've tried everything i know :/

full log here: http://pastebin.com/eE8rM9CT

**Comment by AvalancheYT** [comment]
By the look of the logs, it doesn't seem to download the required dependencies (I may be wrong) properly.

**Comment by LightWarp** [comment]
i did download the TF dependancies
but it gives me another error

**Comment by AvalancheYT** [comment]
Mind uploading it?

**Comment by LightWarp** [comment]
The project folder?

**Comment by AvalancheYT** [comment]
The error code

**Comment by LightWarp** [comment]
the whole src-main folder has errors. should i upload the logs or actual code?

**Comment by AvalancheYT** [comment]
Upload the error logs.

**Comment by LightWarp** [comment]
http://pastebin.com/RQbgVQRZ

**Comment by LightWarp** [comment]
i feel it is something to do with the pom.xml

**Comment by OxLemonxO** [comment]
Download the libraries again.
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\org\spigotmc\spigot\1.11.2\spigot-1.11.2.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\pravian\aero\2.0\aero-2.0.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\totalfreedom\bukkittelnet\4.2\bukkittelnet-4.2.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\totalfreedom\tf-worldedit\6.1.0-TF\tf-worldedit-6.1.0-TF.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\totalfreedom\tf-essentials\2.0-TF\tf-essentials-2.0-TF.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\me\libaryaddict\LibsDisguises\9.2.4\LibsDisguises-9.2.4.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\dv8tion\JDA\2.3.0_379\JDA-2.3.0_379.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\org\spigotmc\spigot\1.11.2\spigot-1.11.2.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\pravian\aero\2.0\aero-2.0.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\totalfreedom\bukkittelnet\4.2\bukkittelnet-4.2.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\totalfreedom\tf-worldedit\6.1.0-TF\tf-worldedit-6.1.0-TF.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\totalfreedom\tf-essentials\2.0-TF\tf-essentials-2.0-TF.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\me\libaryaddict\LibsDisguises\9.2.4\LibsDisguises-9.2.4.jar; error in opening zip file
error reading C:\Users\MADHAV KOTHANDARAMAN\.m2\repository\net\dv8tion\JDA\2.3.0_379\JDA-2.3.0_379.jar; error in opening zip file

**Comment by LightWarp** [comment]
it says TF-Essentials, but there is UMC-Essentials in the lib, do i still need to download them?

**Comment by LightWarp** [comment]
This is what happens if i download the libraries, idk if its the same error, 
http://pastebin.com/aG2gwaH9

the image attached is a screenshot of my lib folder contents. 
![for github](https://cloud.githubusercontent.com/assets/25707656/22862972/71f9478c-f173-11e6-85d3-8936cbdd37c7.PNG)

**Comment by OutOfYourMind** [comment]
I think Seth changed it to where you can only use Eclipse to compile UMC-Mod.

**Comment by CreeperSeth** [comment]
What Lemon said, I've converted the project back to netbeans a couple months ago.

**Comment by LightWarp** [comment]
i am using netbeans btw

**Comment by robingall2910** [comment]
> it says TF-Essentials, but there is UMC-Essentials in the lib, do i still need to download them?

Redownload everything else except TF-Essentials and TF-WorldEdit, those aren't needed.
