### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by BlazingFlames** [UnraveledMC/UnraveledMCMod#8]
Hi there,

I was wondering how I can compile UMCM as when I try to compile with netbeans I get the following error:

Failed to execute goal on project UnraveledMCMod: Could not resolve dependencies for project me.unraveledmc:UnraveledMCMod:jar:2.0: The following artifacts could not be resolved: org.projectlombok:lombok:jar:1.16.6, org.spigotmc:spigot:jar:1.12, net.pravian:aero:jar:2.0, net.totalfreedom:bukkittelnet:jar:4.5, net.totalfreedom:umc-worldedit:jar:6.1.0-UMC, net.totalfreedom:umc-essentials:jar:2.0-UMC, me.libaryaddict:LibsDisguises:jar:9.2.4, net.dv8tion:JDA:jar:2.3.0_379, net.coreprotect:CoreProtect:jar:2.14.2: Could not find artifact org.projectlombok:lombok:jar:1.16.6 at specified path D:\UMC\UnraveledMCMod-master\lib\lombok-1.16.6.jar -> [Help 1]

Thanks!

**Comment by LightWarp** [comment]
You may need to manually install the dependencies.

**Comment by BlazingFlames** [comment]
I am also getting this error with UMC-LibsDisguises (different dependencies obviously) and UMC-Essentials.

**Comment by BlazingFlames** [comment]
How do I do that with all of those dependencies?

**Comment by Raduyno** [comment]
Hello. If you can give me your discord username we will talk there. I know very good to compile UMC Mod and I can help you.

**Comment by BlazingFlames** [comment]
@Raduyno Blazing_Flames#4780

**Comment by BlazingFlames** [comment]
This issue is also happening with UMC-LibsDisguises and UMC-Essentials.

**Comment by CreeperSeth** [comment]
I've sent you the required libraries over discord. However some might be outdated as it was an out zip and I don't feel like re-zipping them

**Comment by CreeperSeth** [comment]
Issue resolved
