### ISSUE TITLE
WorldEdit //set

### ISSUE THREAD

**Issue by BlazingFlames** [UnraveledMC/UnraveledMCMod#9]
Hi there,

UMC-WorldEdit wont work for me on 1.12. When I try to use //set it comes up with this error: http://i.imgur.com/yNOfGCf.png

This is the console after using //set:

https://pastebin.com/4AW66JnV

I believe I need UMC-WorldEdit 6.1.8 but I don't know where I can get that from.

Any help is appreciated, thanks.

**Comment by LightWarp** [comment]
make sure you have the latest release here: https://github.com/UnraveledMC/UMC-WorldEdit/releases

**Comment by BlazingFlames** [comment]
I do indeed @LightWarp

**Comment by BlazingFlames** [comment]
Bump

**Comment by ItzLevvie** [comment]
@BlazingFlames https://github.com/TotalFreedom/TotalFreedomMod/issues/2086#issuecomment-317806755

Make sure to go on https://github.com/ItzLevvie/TF-WorldEdit/blob/f6ee6e395f85932cee161506c3937777846b9d88/worldedit-core/src/main/java/me/totalfreedom/worldedit/WorldEditHandler.java#L147 and change ```TotalFreedomMod``` to ```UnraveledMCMod``` and compile using the ```gradlew build``` command.
